name: flutter_web
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  idb_shim: ^2.4.1+1
  go_router: ^14.1.1
  equatable: ^2.0.5
  hive: ^2.2.3
  path_provider: ^2.1.3
  gap: ^3.0.1
  uuid: ^4.4.0
  flutter_screenutil: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true































